// Curated common meals a new user can seed into their account (A1). Kept
// deliberately minimal — title, a couple of collection tags, the standard raw
// materials you'd shop for, plus ballpark per-serving macros. Each is created
// as a normal recipe via POST /recipes, so the user can edit or delete them
// afterwards. Macros are rough estimates (macros_source: "estimated").

export interface StarterRecipe {
  title: string;
  tags: string[];
  ingredients: string[];
  servings: number;
  // Per serving, ballpark.
  calories: number;
  protein_g: number;
  carb_g: number;
  fat_g: number;
}

export const STARTER_RECIPES: StarterRecipe[] = [
  {
    title: "Spaghetti Bolognese",
    tags: ["Beef", "Pasta"],
    ingredients: [
      "Beef mince",
      "Spaghetti",
      "Onion",
      "Garlic",
      "Carrot",
      "Celery",
      "Chopped tomatoes",
      "Tomato purée",
      "Beef stock",
      "Olive oil",
    ],
    servings: 4,
    calories: 600,
    protein_g: 32,
    carb_g: 70,
    fat_g: 20,
  },
  {
    title: "Chilli Con Carne",
    tags: ["Beef", "Spicy"],
    ingredients: [
      "Beef mince",
      "Rice",
      "Onion",
      "Garlic",
      "Red pepper",
      "Kidney beans",
      "Chopped tomatoes",
      "Tomato purée",
      "Cumin",
      "Chilli powder",
      "Beef stock",
    ],
    servings: 4,
    calories: 550,
    protein_g: 30,
    carb_g: 65,
    fat_g: 18,
  },
  {
    title: "Chicken Fajitas",
    tags: ["Chicken"],
    ingredients: [
      "Chicken breast",
      "Tortilla wraps",
      "Onion",
      "Red pepper",
      "Green pepper",
      "Fajita seasoning",
      "Olive oil",
    ],
    servings: 4,
    calories: 520,
    protein_g: 38,
    carb_g: 55,
    fat_g: 15,
  },
  {
    title: "Cheeseburger & Chips",
    tags: ["Beef"],
    ingredients: [
      "Beef mince",
      "Burger buns",
      "Cheddar cheese",
      "Chips",
      "Lettuce",
      "Tomato",
      "Onion",
      "Ketchup",
    ],
    servings: 4,
    calories: 750,
    protein_g: 35,
    carb_g: 60,
    fat_g: 40,
  },
  {
    title: "Sausage Carbonara",
    tags: ["Pork", "Pasta"],
    ingredients: [
      "Sausages",
      "Spaghetti",
      "Eggs",
      "Parmesan",
      "Garlic",
      "Black pepper",
      "Olive oil",
    ],
    servings: 4,
    calories: 700,
    protein_g: 30,
    carb_g: 75,
    fat_g: 30,
  },
  {
    title: "Steak & Chips",
    tags: ["Beef"],
    ingredients: ["Steak", "Chips", "Garlic", "Butter", "Olive oil"],
    servings: 2,
    calories: 650,
    protein_g: 45,
    carb_g: 45,
    fat_g: 32,
  },
  {
    title: "Chicken Gyros",
    tags: ["Chicken"],
    ingredients: [
      "Chicken thighs",
      "Flatbreads",
      "Garlic",
      "Lemon",
      "Natural yogurt",
      "Oregano",
      "Tomato",
      "Red onion",
      "Cucumber",
    ],
    servings: 4,
    calories: 550,
    protein_g: 40,
    carb_g: 50,
    fat_g: 20,
  },
  {
    title: "Jerk Chicken",
    tags: ["Chicken", "Spicy"],
    ingredients: [
      "Chicken thighs",
      "Jerk seasoning",
      "Lime",
      "Garlic",
      "Spring onion",
      "Rice",
      "Kidney beans",
    ],
    servings: 4,
    calories: 520,
    protein_g: 38,
    carb_g: 55,
    fat_g: 14,
  },
  {
    title: "Oven Pizza",
    tags: ["Vegetarian"],
    ingredients: ["Pizza base", "Passata", "Mozzarella", "Basil", "Olive oil"],
    servings: 2,
    calories: 600,
    protein_g: 25,
    carb_g: 70,
    fat_g: 22,
  },
  {
    title: "Fish & Chips",
    tags: ["Fish"],
    ingredients: [
      "Cod fillets",
      "Potatoes",
      "Plain flour",
      "Sparkling water",
      "Garden peas",
      "Vegetable oil",
    ],
    servings: 2,
    calories: 800,
    protein_g: 35,
    carb_g: 80,
    fat_g: 38,
  },
  {
    title: "Chicken Pie",
    tags: ["Chicken"],
    ingredients: [
      "Chicken breast",
      "Puff pastry",
      "Onion",
      "Leek",
      "Butter",
      "Plain flour",
      "Chicken stock",
      "Double cream",
    ],
    servings: 4,
    calories: 650,
    protein_g: 32,
    carb_g: 55,
    fat_g: 34,
  },
  {
    title: "Shepherd's Pie",
    tags: ["Lamb"],
    ingredients: [
      "Lamb mince",
      "Potatoes",
      "Onion",
      "Carrot",
      "Garden peas",
      "Tomato purée",
      "Beef stock",
      "Butter",
      "Milk",
    ],
    servings: 4,
    calories: 520,
    protein_g: 30,
    carb_g: 45,
    fat_g: 22,
  },
  {
    title: "Roast Chicken Dinner",
    tags: ["Chicken"],
    ingredients: [
      "Whole chicken",
      "Potatoes",
      "Carrots",
      "Broccoli",
      "Gravy granules",
      "Olive oil",
    ],
    servings: 4,
    calories: 600,
    protein_g: 45,
    carb_g: 45,
    fat_g: 25,
  },
  {
    title: "Beef Stew",
    tags: ["Beef"],
    ingredients: [
      "Stewing beef",
      "Potatoes",
      "Carrots",
      "Onion",
      "Celery",
      "Beef stock",
      "Plain flour",
      "Bay leaves",
    ],
    servings: 4,
    calories: 480,
    protein_g: 38,
    carb_g: 40,
    fat_g: 18,
  },
  {
    title: "Mac & Cheese",
    tags: ["Vegetarian", "Pasta"],
    ingredients: [
      "Macaroni",
      "Cheddar cheese",
      "Butter",
      "Plain flour",
      "Milk",
      "Breadcrumbs",
    ],
    servings: 4,
    calories: 650,
    protein_g: 26,
    carb_g: 70,
    fat_g: 30,
  },
  {
    title: "Fish Pie",
    tags: ["Fish"],
    ingredients: [
      "White fish",
      "Salmon fillets",
      "Potatoes",
      "Butter",
      "Plain flour",
      "Milk",
      "Garden peas",
      "Cheddar cheese",
    ],
    servings: 4,
    calories: 520,
    protein_g: 35,
    carb_g: 45,
    fat_g: 20,
  },
  {
    title: "Chicken Curry & Rice",
    tags: ["Chicken", "Spicy"],
    ingredients: [
      "Chicken breast",
      "Rice",
      "Onion",
      "Garlic",
      "Ginger",
      "Curry paste",
      "Chopped tomatoes",
      "Coconut milk",
    ],
    servings: 4,
    calories: 600,
    protein_g: 35,
    carb_g: 70,
    fat_g: 20,
  },
  {
    title: "Bangers & Mash",
    tags: ["Pork"],
    ingredients: ["Sausages", "Potatoes", "Onion", "Gravy granules", "Butter", "Milk"],
    servings: 4,
    calories: 620,
    protein_g: 25,
    carb_g: 60,
    fat_g: 32,
  },
  {
    title: "Tuna Pasta Bake",
    tags: ["Fish", "Pasta"],
    ingredients: [
      "Pasta",
      "Tinned tuna",
      "Sweetcorn",
      "Cheddar cheese",
      "Milk",
      "Plain flour",
      "Butter",
    ],
    servings: 4,
    calories: 550,
    protein_g: 32,
    carb_g: 68,
    fat_g: 16,
  },
];
